DEFAULT_ENV_SAMPLES_FILENAME="env_samples.csv"
DEFAULT_STATE_MAP_FILENAME="state_map.csv"
DEFAULT_QTABLE_FILENAME="qtable.csv"
GYM_ENV_NAME="ALE/Centipede-ram-v5"
FRAME_SKIP=40
REPEAT_ACTION_PROBABILITY=0.05
DEFAULT_RENDER_MODE=None